---
- hosts: localhost 
  connection: local
  tasks:
    - name: copy war into tomcat
      copy:
        src: /home/ec2-user/Manavae-web-app-2/Java-Ansible/target/Java-Ansible.war
        dest: /usr/local/tomcat/webapps
    - name: Starting tomcat
      shell: nohup /usr/local/tomcat/bin/startup.sh &
